version: '3'
services:
  unifi_controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=987
      - PGID=114
    networks:
      - web
    volumes:
      - ${CONF_DIR}/unifi_controller:/config
    expose:
      - "8443"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unificontroller.rule=Host(`unifi.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.unificontroller.entrypoints=websecure"
      - "traefik.http.routers.unificontroller.tls=true"
      - "traefik.http.services.unificontroller.loadbalancer.server.port=8443"
  vpn:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    environment:
      TZ: Europe/Berlin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ${CONF_DIR}/openvpn:/vpn
    ports:
      - "8680:8080" # SABNZBD
      - "9090:9090" # SABNZBD
    command: "-r 192.168.1.0/24"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    expose:
      - "8989"
    networks: 
      - "web"
    ports:
      - "8989:8989"
    environment:
      TZ: "Europe/Berlin"
      PUID: 997
      PGID: 114
    volumes:
      - ${CONF_DIR}/sonarr:/config
      - tvshows:/tv
      - downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    expose:
      - "7878"
    networks: 
      - "web"
    ports:
      - "7878:7878"
    depends_on:
      - vpn
    environment:
      TZ: "Europe/Berlin"
      PUID: 993
      PGID: 114
    volumes:
      - ${CONF_DIR}/radarr:/config
      - movies:/movies
      - downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    expose:
      - "8181"
    networks: 
      - "web"
    environment:
      TZ: "Europe/Berlin"
      PUID: 992
      PGID: 114
    volumes:
      - ${CONF_DIR}/tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
  heimdall :
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - web
      - default
    environment:
      TZ: "Europe/Berlin"
      PUID: 991
      PGID: 114
    volumes:
      - ${CONF_DIR}/heimdall:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    environment:
      TZ: "Europe/Berlin"
      VERSION: latest
      PUID: 995
      PGID: 114
    volumes:
      - ${CONF_DIR}/sabnzbd:/config
      - movies:/movies
      - downloads:/downloads
  unifi_nvr:
    image: pducharme/unifi-video-controller
    container_name: unifi_nvr
    restart: unless-stopped
    networks:
      - web
      - default
    environment:
      PUID: 989
      PGID: 114
    volumes:
      - '${UNIFI_CONFIG_DIR}:/var/lib/unifi-video'
      - '${UNIFI_VIDEO_DIR}:/var/lib/unifi-video/videos'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    expose:
      - "7080"
    networks: 
      - "web"
    ports:
     - "10001:10001"
     - "1935:1935"
     - "6666:6666"
     - "7004:7004"
     - "7080:7080"
     - "7442:7442"
     - "7443:7443"
     - "7444:7444"
     - "7445:7445"
     - "7446:7446"
     - "7447:7447"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifinvr.rule=Host(`nvr.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.unifinvr.entrypoints=websecure"
      - "traefik.http.routers.unifinvr.tls=true"
      - "traefik.http.services.unifinvr.loadbalancer.server.port=7080"
  deconz:
    image: marthoc/deconz
    container_name: deconz_service
    restart: unless-stopped
    ports:
      - "40850:40850"
      - "40860:40860"
      - "40870:40870"
    volumes:
      - ${DECONZ_CONFIG_DIR}:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=40850
      - DECONZ_WS_PORT=40860
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=40870
      - DECONZ_VNC_PASSWORD=geheim123
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTAU=1
      - DECONZ_DEVICE=/dev/ttyACM0
  facebox:
    image: machinebox/facebox_noavx
    container_name: facebox
    restart: unless-stopped
    networks:
      - web
    ports:
      - "8280:8080"
    expose: 
      - "8080"
    networks: 
      - "web"
    expose:
      - 8080
    environment:
      - MB_KEY=${FACEBOX_MB_KEY}
      - MB_FACEBOX_DISABLE_RECOGNITION=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.facebox.rule=Host(`facebox.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.facebox.tls=true"
      - "traefik.http.routers.facebox.entrypoints=websecure"
  traefik:
    image: traefik:v2.0
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/etc/traefik/acme.json"
      - "--providers.file.filename=/etc/traefik/dyn-traefik.yaml"
      - "--providers.file.watch=true"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_dashboard.rule=Host(`traefik.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.traefik_dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik_dashboard.tls=true"
      - "traefik.http.services.traefik_dashboard.loadbalancer.server.port=8080"
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8456:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONF_DIR}/traefik:/etc/traefik
  # adguard:
  #   image: adguard/adguardhome
  #   container_name: adguard
  #   restart: unless-stopped
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #   expose:
  #     - "80"
  #   ports:
  #     - '53:53'
  #     - '67:67/udp'
  #     - '68:68'
  #     - '853:853/tcp'
  #     - '3000:3000/tcp'
  #     - '8780:80/tcp'
  #   networks:
  #     - web
  #   volumes:
  #     - ${CONF_DIR}/adguard:/opt/adguardhome/conf
  #     - ${ADGUARD_DATA_DIR}:/opt/adguardhome/work
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.adguard.rule=Host(`adguard.${TRAEFIK_EXTERNAL_DOMAIN}`)"
  #     - "traefik.http.routers.adguard.entrypoints=websecure"
  #     - "traefik.http.routers.adguard.tls.certresolver=mytlschallenge"
  #     - "traefik.http.services.adguard.loadbalancer.server.port=80"
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: unless-stopped
    networks:
      - web
    expose:
      - "80"
    environment:
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN: ${BITWARDEN_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: "true"
    volumes:
      - ${CONF_DIR}/bitwarden/:/data/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.bitwarden.entrypoints=websecure"
      - "traefik.http.routers.bitwarden.tls.certresolver=mytlschallenge"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
  node_red:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nodered
      args:
        NPM_PACKAGES: "node-red-contrib-light-scheduler node-red-contrib-config node-red-contrib-fs"
    expose:
    - "1880"
    networks: 
      - "web"
    volumes: 
      - ${CONF_DIR}/nodered:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node_red.rule=Host(`red.${TRAEFIK_EXTERNAL_DOMAIN}`)"
      - "traefik.http.routers.node_red.tls=true"
      - "traefik.http.routers.node_red.entrypoints=websecure"


networks:
  default:
  web:
    external: true

volumes:
  tvshows:
    driver: local
    driver_opts:
      type: none
      device: ${TVSHOW_DIR}
      o: bind
  movies:
    driver: local
    driver_opts:
      type: none
      device: ${MOVIE_DIR}
      o: bind
  downloads:
    driver: local
    driver_opts:
      type: none
      device: ${DOWNLOAD_DIR}
      o: bind
  incomplete_downloads:
    driver: local
    driver_opts:
      type: none
      device: ${DOWNLOAD_DIR}/incomplete
      o: bind