version: '3'
services:
  vpn:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    security_opt: 
      - label:disable
    environment: 
      TZ: Europe/Berlin
    networks: 
      - default
    read_only: true
    tmpfs: 
      - /run
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes: 
      - /dev/net:/dev/net:z
      - ${CONF_DIR}/openvpn:/vpn
    ports: 
      - "8080:8080" # SABNZBD
      - "9090:9090" # SABNZBD
    command: "-r 192.168.178.0/24"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      PUID: 997
      PGID: 114
    volumes:
      - ${CONF_DIR}/sonarr:/config
      - tvshows:/tv
      - downloads:/downloads
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      PUID: 993
      PGID: 114
    volumes:
      - ${CONF_DIR}/radarr:/config
      - movies:/movies
      - downloads:/downloads
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    environment: 
      TZ: "Europe/Berlin"
      PUID: 992
      PGID: 114
    volumes:
      - ${CONF_DIR}/tautulli:/config
  heimdall :
    image: linuxserver/heimdall 
    container_name: heimdall 
    restart: unless-stopped
    ports: 
      - 8090:80
      - 8043:443
    environment: 
      TZ: "Europe/Berlin"
      PUID: 991
      PGID: 114
    volumes:
      - ${CONF_DIR}/heimdall:/config
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      VERSION: latest
      PUID: 995
      PGID: 114
    volumes:
      - ${CONF_DIR}/sabnzbd:/config
      - movies:/movies
      - downloads:/downloads
  unifi_nvr:
    image: pducharme/unifi-video-controller
    container_name: unifi_nvr
    restart: unless-stopped
    environment: 
      PUID: 989
      PGID: 114
    volumes: 
      - '${UNIFI_CONFIG_DIR}:/var/lib/unifi-video'
      - '${UNIFI_VIDEO_DIR}:/var/lib/unifi-video/videos'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    ports:
     - "10001:10001"
     - "1935:1935"
     - "6666:6666"
     - "7004:7004"
     - "7080:7080"
     - "7442:7442"
     - "7443:7443"
     - "7444:7444"
     - "7445:7445"
     - "7446:7446"
     - "7447:7447"
  deconz:
    image: marthoc/deconz
    container_name: deconz_service
    restart: unless-stopeed
    ports:
      - "40850:40850"
      - "40860:40860"
      - "40870:40870"
    volumes:
      - ${DECONZ_CONFIG_DIR}:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=40850
      - DECONZ_WS_PORT=40860
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=40870
      - DECONZ_VNC_PASSWORD=geheim123
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTAU=1
      - DECONZ_DEVICE=/dev/ttyACM0

networks:
  default:

volumes: 
  tvshows:
    driver: local
    driver_opts: 
      type: none
      device: ${TVSHOW_DIR}
      o: bind
  movies:
    driver: local
    driver_opts: 
      type: none
      device: ${MOVIE_DIR}
      o: bind
  downloads:
    driver: local
    driver_opts: 
      type: none
      device: ${DOWNLOAD_DIR}
      o: bind
  incomplete_downloads:
    driver: local
    driver_opts: 
      type: none
      device: ${DOWNLOAD_DIR}/incomplete
      o: bind