version: '3'
services:
  vpn:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    security_opt: 
      - label:disable
    environment: 
      TZ: Europe/Berlin
    networks: 
      - default
    read_only: true
    tmpfs: 
      - /run
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes: 
      - /dev/net:/dev/net:z
      - /media/server/config/openvpn:/vpn
    ports: 
      - "8989:8989" # SONARR
      - "7878:7878" # RADARR
      - "8080:8080" # SABNZBD
      - "9090:9090" # SABNZBD
    command: "-r 192.168.178.0/24"
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      PUID: 997
      PGID: 114
    volumes:
      - /media/server/config/sonarr:/config
      - tvshows:/tv
      - downloads:/downloads
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      PUID: 993
      PGID: 114
    volumes:
      - /media/server/config/radarr:/config
      - movies:/movies
      - downloads:/downloads
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    environment: 
      TZ: "Europe/Berlin"
      PUID: 992
      PGID: 114
    volumes:
      - /media/server/config/tautulli:/config
  heimdall :
    image: linuxserver/heimdall 
    container_name: heimdall 
    restart: unless-stopped
    ports: 
      - 8090:80
      - 8043:443
    environment: 
      TZ: "Europe/Berlin"
      PUID: 991
      PGID: 114
    volumes:
      - /media/server/config/heimdall:/config
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      VERSION: latest
      PUID: 995
      PGID: 114
    volumes:
      - /media/server/config/sabnzbd:/config
      - movies:/movies
      - downloads:/downloads
  # plex:
  #   image: linuxserver/plex
  #   container_name: plex
  #   network_mode: "service:vpn"
  #   restart: unless-stopped
  #   depends_on: 
  #     - vpn
  #   environment: 
  #     VERSION: docker
  #     PUID: 996
  #     PGID: 114
  #   volumes:
  #     - /media/server/config/plex:/config
  #     - tvshows:/tv
  #     - movies:/movies
  #     - /media/server/media/transcoding:/transcode
  # couchpotato:
  #   image: linuxserver/couchpotato
  #   container_name: couchpotato
  #   network_mode: "service:vpn"
  #   restart: unless-stopped
  #   depends_on:
  #     - vpn
  #   environment: 
  #     TZ: "Europe/Berlin"
  #     VERSION: latest
  #     PUID: 998
  #     PGID: 114
  #   volumes:
  #     - /media/server/config/couchpotato:/config
  #     - movies:/movies
  #     - downloads:/downloads

networks:
  default:

volumes: 
  tvshows:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/tvshows
      o: bind
  movies:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/movies
      o: bind
  downloads:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/downloads
      o: bind
  incomplete_downloads:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/downloads/incomplete
      o: bind