version: '3'
services:
  vpn:
    image: dperson/openvpn-client
    container_name: openvpn
    cap_add:
      - net_admin
    security_opt: 
      - label:disable
    environment: 
      TZ: Europe/Berlin
    networks: 
      - default
    read_only: true
    tmpfs: 
      - /run
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes: 
      - /dev/net:/dev/net:z
      - /media/server/config/openvpn:/vpn
    ports: 
      - "32400:32400" # PLEX
      - "32400:32400/udp" # PLEX
      - "32469:32469" # PLEX
      - "32469:32469/udp" # PLEX
      - "1900:1900/udp" # PLEX
      - "8989:8989" # SONARR
      - "5050:5050" # Couchpotato
      - "8080:8080" # SABNZBD
      - "9090:9090" # SABNZBD
    command: "-r 192.168.178.0/24"
  plex:
    image: linuxserver/plex
    container_name: plex
    user: plex
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on: 
      - vpn
    environment: 
      VERSION: docker
      PUID: 996
      GUID: 114
    volumes:
      - /media/server/config/plex:/config
      - tvshows:/data/tv
      - movies:/data/movies
      - /media/server/media/transcoding:/data/transcoding
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    user: sonarr
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      PUID: 997
      GUID: 114
    volumes:
      - /media/server/config/sonarr:/config
      - tvshows:/data/tv
      - downloads:/downloads
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    user: couchpotato
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      VERSION: latest
      PUID: 998
      GUID: 114
    volumes:
      - /media/server/config/couchpotato:/config
      - movies:/data/movies
      - downloads:/downloads
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    user: sabnzbd
    network_mode: "service:vpn"
    restart: unless-stopped
    depends_on:
      - vpn
    environment: 
      TZ: "Europe/Berlin"
      VERSION: latest
      PUID: 995
      GUID: 114
    volumes:
      - /media/server/config/sabnzbd:/config
      - movies:/data/movies
      - downloads:/downloads

networks:
  default:

volumes: 
  tvshows:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/tvshows
      o: bind
  movies:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/movies
      o: bind
  downloads:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/media/downloads
      o: bind