debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "janz.digital"
watch = true
exposedbydefault = false

[acme]
email = "janz.jonas@gmail.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true