version: "3"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz_service
    restart: unless-stopeed
    ports:
      - "40850:40850"
      - "40860:40860"
      - "40870:40870"
    volumes:
      - deconz_config:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=40850
      - DECONZ_WS_PORT=40860
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=40870
      - DECONZ_VNC_PASSWORD=geheim123
      - DEBUG_INFO=1
      - DEBUG_APS=1
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTAU=1
      - DECONZ_DEVICE=/dev/ttyACM0

volumes: 
  deconz_config:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/deconz
      o: bind