version: '3'
services:
  7days2die:
    image: didstopia/7dtd-server
    container_name: 7dtd-server
    environment:
      PUID: 984
      PGID: 114
      SEVEN_DAYS_TO_DIE_TELNET_PASSWORD: $TELNET_PASSWORD
    networks:
      - web
      - default
    volumes:
      - ${CONF_DIR}:/app/.local/share/7DaysToDie
      - ${GAME_DIR}:/steamcmd/7dtd
    ports:
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
      - 8070:8080/tcp
      - 8071:8081/tcp
    restart: unless-stopped

networks:
  default:
  web:
    external: true