version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft_server
    restart: unless-stopped
    ports: 
      - "25565:25565"
    environment: 
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.13.2"
      SERVER_NAME: "${MINECRAFT_SERVER_NAME}"
      DIFFICULTY: "${MINECRAFT_DIFFICULTY}"
      WHITELIST: "${MINECRAFT_WHITELIST}"
      OPS: "${MINECRAFT_OPS}"
      ENABLE_RCON: "TRUE"
      RCON_PASSWORD: "${MINECRAFT_RCON_PASSWORD}"
      MAX_PLAYERS: 20
      MODE: "survival"
      MOTD: "Welcome to the ${MINECRAFT_SERVER_NAME} Server. Enjoy your stay"
      LEVEL: "test"
    volumes: 
      - ${CONF_DIR}/plugins.yml:/plugins.yml
      - ${MINECRAFTR_SERVER_DIR}:/data