version: "3"
services:
  deconz:
    image: pducharme/unifi-video-controller
    container_name: unifi_nvr
    restart: unless-stopped
    volumes: 
      - 'unifi_config:/var/lib/unifi-video'
      - 'unifi_videos:/var/lib/unifi-video/videos'
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    ports:
     - "10001:10001"
     - "1935:1935"
     - "6666:6666"
     - "7004:7004"
     - "7080:7080"
     - "7442:7442"
     - "7443:7443"
     - "7444:7444"
     - "7445:7445"
     - "7446:7446"
     - "7447:7447"

volumes: 
  unifi_videos:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/unifi/videos
      o: bind
  unifi_config:
    driver: local
    driver_opts: 
      type: none
      device: /media/server/unifi/configuration
      o: bind